---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Install Git
  action: "{{ packager }} pkg={{ git }} state=latest"
- name: Install Build Essential (Debian)
  action: "{{ packager }} pkg='{{ build_essential }}' state=present"
  when: ansible_os_family == "Debian"
- name: Install Vim
  apt: pkg=vim state=present
  when: ansible_os_family == "Debian"
- name: Install GraphViz
  action: "{{ packager }} pkg=graphviz state=latest"
- name: Install Man
  action: "{{ packager }} pkg=man state=latest"
- name: Copy setup-site Application
  copy: src=setup-site dest=/usr/bin/setup-site owner=root group=root mode=0755
- name: Copy setup-database Application
  copy: src=setup-database dest=/usr/bin/setup-database owner=root group=root mode=0755
- name: Copy setup-xdebug Application
  copy: src=setup-xdebug dest=/usr/bin/setup-xdebug owner=root group=root mode=0755

- name: Node.js | Exists
  stat: path=/usr/bin/node
  register: installed_node
- name: Node.js | Download source
  get_url: url=http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz dest=/tmp/
  when: installed_node.stat.exists == false
- name: Node.js | Extract tarball
  command: tar -zxf /tmp/node-v0.10.24.tar.gz chdir=/tmp
  when: installed_node.stat.exists == false
- name: Node.js | Configure
  shell: ./configure --prefix=/usr chdir=/tmp/node-v0.10.24
  when: installed_node.stat.exists == false
- name: Node.js | Make
  shell: make chdir=/tmp/node-v0.10.24
  when: installed_node.stat.exists == false
- name: Node.js | Make install
  shell: make install chdir=/tmp/node-v0.10.24
  when: installed_node.stat.exists == false
- name: Node.js | Gulp exists
  stat: path=/usr/bin/gulp
  register: installed_gulp
- name: Node.js | Install gulp
  command: npm install -g gulp
  when: installed_gulp.stat.exists == false
