---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Install Git
  action: "{{ packager }} pkg={{ git }} state=present"
- name: Install Build Essential (Debian)
  action: "{{ packager }} pkg='{{ build_essential }}' state=present"
  when: ansible_os_family == "Debian"
- name: Install Vim
  apt: pkg=vim state=present
  when: ansible_os_family == "Debian"
- name: Install GraphViz
  action: "{{ packager }} pkg=graphviz state=present"
- name: Install Man
  action: "{{ packager }} pkg=man state=present"
- name: Copy setup-site Application
  copy: src=setup-site dest=/usr/bin/setup-site owner=root group=root mode=0755
- name: Copy setup-database Application
  copy: src=setup-database dest=/usr/bin/setup-database owner=root group=root mode=0755
- name: Copy setup-xdebug Application
  copy: src=setup-xdebug dest=/usr/bin/setup-xdebug owner=root group=root mode=0755
#- name: Add {{ dev_user }} to the users group
#  user: name={{ dev_user }} append=yes groups=users
#  when: groups['developer'] is defined
