---
#- name: Load vars for this distro
#  include_vars: "{{ ansible_os_family }}.yml"
- name: Install Nginx
  action: "{{ packager }} pkg=nginx state=present"
- name: Configure nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
- name: Configure Nginx includes for sites
  copy: src=conf.d dest=/etc/nginx
  notify: reload nginx
- name: Configure who can view the PHP-FPM status and pings
  template: src=can_view_fpm_status.conf.j2
            dest=/etc/nginx/conf.d/can_view_fpm_status.conf
  notify: reload nginx

- name: Configure default Nginx site
  template: src=default_site.conf.j2
            dest=/etc/nginx/sites-available/default
  notify: reload nginx
- name: Enable default Nginx Site
  file: src=/etc/nginx/sites-available/default
        dest=/etc/nginx/sites-enabled/default
        state=link
  notify: reload nginx

- name: Configure Nginx sites
  template: src=site.conf.j2
            dest="/etc/nginx/sites-available/{{ item.key | replace('__hostname__', hostname) }}.conf"
  with_dict: websites
  notify: reload nginx
- name: Enable Nginx Sites
  file: src="/etc/nginx/sites-available/{{ item.key | replace('__hostname__', hostname) }}.conf"
        dest="/etc/nginx/sites-enabled/{{ item.key | replace('__hostname__', hostname) }}.conf"
        state=link
  with_dict: websites
  notify: reload nginx

- name: Configure Nginx Mailblock site for development
  template: src=site_mailblock.conf.j2
            dest=/etc/nginx/sites-available/mailblock.conf
  notify: reload nginx
  when: "'developer' in group_names"
- name: Enable Nginx mailblock site for development
  file: src=/etc/nginx/sites-available/mailblock.conf
        dest=/etc/nginx/sites-enabled/mailblock.conf
        state=link
  notify: reload nginx
  when: "'developer' in group_names"

- name: When Varnish is used, only allow access to Nginx from management IPs
  ufw: rule=allow port={{ item[0] }} from_ip={{ item[1] }}
  with_nested:
  - [ "{{ nginx_port }}", "{{ nginx_spdy_port }}" ]
  - management_ips
  when: varnish
- name: When Varnish is disabled, allow unrestricted access to Nginx
  ufw: rule=allow port={{ item[0] }}
  with_nested:
  - "{{ nginx_port }}"
  - "{{ nginx_spdy_port }}"
  when: not varnish
