---
#- name: Load vars for this distro
#  include_vars: "{{ ansible_os_family }}.yml"
- name: Install dependencies
  action: "{{ packager }} pkg={{ item }} state=present"
  with_items:
  - libpcre3-dev
  - zlib1g-dev
- name: Install HAProxy 1.5 PPA
  apt_repository: repo='ppa:vbernat/haproxy-1.5'
- name: Install HAProxy 1.5
  apt: pkg=haproxy state=latest
- name: Configure HAProxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: reload haproxy
- name: Allow HAProxy through UFW
  ufw: rule=allow port={{ item }}
  with_items:
  - "{{ haproxy_port }}"
  - "{{ haproxy_ssl_port }}"
