---
- hosts: all
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - firewall
  - ssh
  - base
  - git

- hosts: webserver
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - { role: nginx,   when: nginx   == true }
  - { role: varnish, when: varnish == true }
  - { role: haproxy, when: haproxy == true }
  - { role: apache2, when: apache  == true }
  - php
  - node

- hosts: webserver
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  roles:
  - websites

- hosts: database
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - mysql

- hosts: developer
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - developer
  - mailblock

- hosts: all
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - firewall_save
