---
- hosts: all
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - firewall
  - ssh

- hosts: all
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - base
  - git

- hosts: webserver
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  roles:
  - websites

- hosts: webserver
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - ssl
  - { role: nginx,   when: nginx   == true }
  - { role: varnish, when: varnish == true }
  - { role: haproxy, when: haproxy == true }
  - { role: apache2, when: apache  == true }
  - php

- hosts: database
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - mysql

- hosts: development
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - node
  - development
  - mailblock

- hosts: all
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - firewall_save
