---
- hosts: all
  sudo: True
  roles:
  - firewall
  - ssh

- hosts: all
  sudo: True
  roles:
  - base

- hosts: webserver
  roles:
  - websites

- hosts: webserver
  sudo: True
  roles:
  - ssl
  - { role: nginx,   when: nginx   == true }
  - { role: varnish, when: varnish == true }
  - { role: haproxy, when: haproxy == true }
  - { role: memcached, when: memcached != false }
  - php

- hosts: database
  sudo: True
  roles:
  - mysql

- hosts: development
  sudo: True
  roles:
  - node
  - development
  - { role: geerlingguy.mailhog }
  - mailblock

- hosts: all
  sudo: True
  roles:
  - firewall_save
