---
- hosts: all
  sudo: True
  roles:
  - base
  - git

- hosts: webserver
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - apache2
  - php
  - phpmyadmin
  - websites

- hosts: database
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - mysql

- hosts: developer
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  roles:
  - developer
  - node
  - ssh
