---
- hosts: all
  sudo: True
  roles:
  - base

- hosts: webserver
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  accelerate: true
  roles:
  - apache2
  - php
# - phpmyadmin

- hosts: database
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  accelerate: true
  roles:
  - mysql

- hosts: developer
  vars_files: [ "vars/{{ ansible_os_family }}.yml" ]
  sudo: True
  accelerate: true
  roles:
  - developer
  - ssh
