---
- hosts: all
  vars_files:
  - [ "vars/main.yml" ]
  - [ "vars/{{ ansible_os_family }}.yml" ]

- hosts: webserver
  roles:
  - apache2
  - php
# - phpmyadmin

- hosts: database
  roles:
  - mysql

- hosts: developer
  roles:
  - developer
  - ssh
