---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Load Apache role's vars for this distro
  include_vars: "roles/apache2/vars/{{ ansible_os_family }}.yml"

- name: Ensure the logs folder exists for all sites
  file: path="/var/www/{{ item.key }}/logs" state=directory
  with_dict: websites
- name: Ensure the public_html folder exists for all sites
  file: path="/var/www/{{ item.key }}/public_html" state=directory
  with_dict: websites

- name: Clone Git
  git: repo="{{ item.value.git.repo }}"
       version="{{ item.value.git.branch | default('master') }}"
       dest="/var/www/{{ item.key }}/public_html"
       accept_hostkey=yes
       update=no
  when: item.value.git is defined
  with_dict: websites

- name: Copy any customized files into the site
  copy: src="website_overrides/{{ item.value.overrides }}/"
        dest="/var/www/{{ item.key }}/public_html"
  when: item.value.overrides is defined
  with_dict: websites

- name: Create a group for each site
  sudo: yes
  group: name="{{ item.key }}" system=yes
  with_dict: websites
  when: "'developer' not in group_names"

- name: Create a user for each site
  sudo: yes
  user: name="{{ item.key }}" group="{{ item.key }}" system=yes createhome=no
  with_dict: websites
  when: "'developer' not in group_names"

- name: Ensure files are owned by the correct user
  sudo: yes
  file: path="/var/www/{{ item.key }}" state=directory owner="{{ item.key }}" group="{{ item.key }}"
  with_dict: websites
  when: "'developer' not in group_names"

- name: Enable sites folder in Apache
  sudo: yes
  template: src=sites.conf.j2 dest="{{ apache2_conf_folder }}/sites.conf"
  notify:
  - restart apache2
