---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Install Apache2
  action: "{{ packager }} pkg={{ apache2 }} state=present"

- name: Remove unused paths
  file: state="absent" path="{{ item }}"
  with_items:
  - /var/www/icons
  - /var/www/error
  - /var/www/cgi-bin
  - /var/www/html
  - "{{ apache2_conf_folder }}/welcome.conf"
  - "{{ apache2_base }}/sites-available/"
  - "{{ apache2_base }}/sites-enabled/"
  - "{{ apache2_base }}/mods-enabled/mpm_event.conf"
  - "{{ apache2_base }}/mods-enabled/mpm_event.load"

- name: Install Apache2 MPM ITK
  action: "{{ packager }} pkg={{ apache2 }}-mpm-itk state=present"

- name: Setup Apache Config
  template: src=apache2.conf.j2 dest={{ apache2_conf_path }}
  notify: restart apache2

- name: Setup ExtendedStatus
  copy: src=extendedstatus.conf dest={{ apache2_conf_folder }}/extendedstatus.conf
  when: "'developer' in group_names"
  notify: restart apache2

- name: Create /var/www/shared
  file: path=/var/www/shared state=directory
  when: "'developer' in group_names"

- name: Grant g:admin access to /var/www
  command: setfacl -Rm g:admin:rwx /var/www
- name: Grant g:admin default access to /var/www
  command: setfacl -dRm g:admin:rwx /var/www

- name: Autostart Apache2
  service: name={{ apache2 }} enabled=yes state=started

- name: Allow Port 80 and 443 through the firewall
  ufw: rule=allow port={{ item }}
  with_items:
  - 80
  - 443
