---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Install Apache2
  action: "{{ packager }} pkg={{ apache2 }} state=present"
- name: Allow port 80 through IPTables
  lineinfile: dest=/etc/sysconfig/iptables
              regexp='^-A INPUT -p tcp --dport 80 -j ACCEPT$'
              line='-A INPUT -p tcp --dport 80 -j ACCEPT'
              insertafter='^-A INPUT -i lo -j ACCEPT$'
  notify: restart iptables
  when: ansible_os_family == "RedHat"

- name: Check if /var/www/icons exists
  stat: path=/var/www/icons
  register: is_icons_unmoved
- name: Move /var/www/icons
  command: "mv -f /var/www/icons /etc/{{ apache2 }}/icons"
  when: is_icons_unmoved.stat.exists

- name: Check if /var/www/error exists
  stat: path=/var/www/error
  register: is_error_unmoved
- name: Move /var/www/error
  command: "mv -f /var/www/error /etc/{{ apache2 }}/error"
  when: is_error_unmoved.stat.exists

- name: Check if /var/www/cgi-bin exists
  stat: path=/var/www/cgi-bin
  register: is_cgibin_unmoved
- name: Move /var/www/cgi-bin
  command: "mv -f /var/www/cgi-bin /etc/{{ apache2 }}/cgi-bin"
  when: is_cgibin_unmoved.stat.exists

- name: Check if /var/www/html exists
  stat: path=/var/www/html
  register: is_html_unmoved
- name: Move /var/www/html
  command: "mv -f /var/www/html /etc/{{ apache2 }}/html"
  when: is_html_unmoved.stat.exists

- name: Remove Apache Welcome config
  file: path={{ apache2_conf_folder }}/welcome.conf state=absent

- name: Setup Apache Config
  template: src=apache2.conf.j2 dest={{ apache2_conf_path }}
  notify: restart apache2

- name: Setup ExtendedStatus
  copy: src=httpd/conf.d/extendedstatus.conf dest={{ apache2_conf_folder }}/extendedstatus.conf
  notify: restart apache2

- name: Setup LandingPage site
  unarchive: src=sites/landingpage.tar.gz dest=/var/www/

- name: Create /var/www/shared
  file: path=/var/www/shared state=directory

- name: Grant g:admin access to /var/www/shared
  command: setfacl -Rm g:admin:rwx /var/www/shared
- name: Grant g:admin default access to /var/www/shared
  command: setfacl -dRm g:admin:rwx /var/www/shared

- name: Autostart Apache2
  service: name={{ apache2 }} enabled=yes state=started
