---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Install Apache2
  action: "{{ packager }} pkg={{ apache2 }} state=present"
- name: Allow port 80 through IPTables
  lineinfile: dest=/etc/sysconfig/iptables
              regexp='^-A INPUT -p tcp --dport 80 -j ACCEPT$'
              line='-A INPUT -p tcp --dport 80 -j ACCEPT'
              insertafter='^-A INPUT -i lo -j ACCEPT$'
  notify: restart iptables
  when: ansible_os_family == "RedHat"

- name: Remove unused paths
  file: state="absent" path="{{ item }}"
  with_items:
  - /var/www/icons
  - /var/www/error
  - /var/www/cgi-bin
  - /var/www/html
  - "{{ apache2_conf_folder }}/welcome.conf"
  - "{{ apache2_base }}/mods-available/"
  - "{{ apache2_base }}/mods-enabled/"
  - "{{ apache2_base }}/sites-available/"
  - "{{ apache2_base }}/sites-enabled/"

- name: Setup Apache Config
  template: src=apache2.conf.j2 dest={{ apache2_conf_path }}
  notify: restart apache2

- name: Setup ExtendedStatus
  copy: src=httpd/conf.d/extendedstatus.conf dest={{ apache2_conf_folder }}/extendedstatus.conf
  notify: restart apache2

- name: Setup LandingPage site
  unarchive: src=sites/landingpage.tar.gz dest=/var/www/
  when: "'developer' in group_names"

- name: Create /var/www/shared
  file: path=/var/www/shared state=directory
  when: "'developer' in group_names"

- name: Grant g:admin access to /var/www
  command: setfacl -Rm g:admin:rwx /var/www
- name: Grant g:admin default access to /var/www
  command: setfacl -dRm g:admin:rwx /var/www

- name: Autostart Apache2
  service: name={{ apache2 }} enabled=yes state=started
