---
- name: Install Apache2 (Debian)
  action: "{{ packager }} pkg={{ apache2 }} state=latest"
- name: Allow port 80 through IPTables
  lineinfile: dest=/etc/sysconfig/iptables
              regexp='^-A INPUT -p tcp --dport 80 -j ACCEPT$'
              line='-A INPUT -p tcp --dport 80 -j ACCEPT'
              insertafter='^-A INPUT -i lo -j ACCEPT$'
  notify: restart iptables
  when: ansible_os_family == "RedHat"
