---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Disable Password Authentication
  lineinfile: dest=/etc/ssh/sshd_config
              line="PasswordAuthentication no"
              regexp=^#?PasswordAuthentication
  notify: Restart SSHD
- name: Enable Agent Forwarding
  lineinfile: dest=/etc/ssh/sshd_config
              line="AllowAgentForwarding yes"
              regexp=^#?AllowAgentForwarding
  notify: Restart SSHD
- name: Create the admin group
  group: name='admin'
- name: Setup the admin group with nopasswd sudo
  lineinfile: dest=/etc/sudoers
              regexp='^%admin'
              line='%admin ALL=(ALL) NOPASSWD:ALL'
- name: Create the user account
  user: name={{ item }} append=yes groups='admin'
  with_items: devs
- name: Copy SSH Keys
  authorized_key: user={{ item }} key="{{ lookup('file', '.ssh/' + item + '/id_rsa.pub') }}"
  with_items: devs
- name: Configure SSH to ForwardAgent when connecting to another devbox
  copy: src=ssh_config dest=/etc/ssh/ssh_config
