---
- name: Install UFW
  apt: pkg="ufw" state="present"

- name: Check if UFW is installed
  stat: path=/usr/sbin/ufw
  register: installed_ufw
- name: Download UFW source
  get_url: url=https://launchpad.net/ufw/{{ ufw_version }}/{{ ufw_version }}/+download/ufw-{{ ufw_version }}.tar.gz dest=/tmp/
  when: installed_ufw.stat.exists == false
- name: Extract tarball
  command: chdir=/tmp tar -zxf /tmp/ufw-{{ ufw_version }}.tar.gz
  when: installed_ufw.stat.exists == false
- name: Install UFW
  command: chdir=/tmp/ufw-{{ ufw_version }} python setup.py install
  when: installed_ufw.stat.exists == false
- name: Install Init script
  command: chdir=/tmp/ufw-{{ ufw_version }} cp doc/upstart.example /etc/init/ufw.conf
  when: installed_ufw.stat.exists == false
- name: Set proper UFW permissions
  shell: chmod -R g-w /etc/ufw /etc/default/ufw /lib/ufw/ufw-init /usr/sbin/ufw
  when: installed_ufw.stat.exists == false
