---
- name: Install MySQL
  action: "{{ packager }} pkg=mysql-server state=present"
- name: Run MySQL on boot
  service: name={{ mysql_service }} enabled=yes state=started
- name: Set MySQL Max Packet Size
  lineinfile: dest={{ mysql_config_path }}
              line="max_allowed_packet=16M"
              regexp=^max_allowed_packet
              insertafter=^\\[mysqld\\]$
  notify: Restart MySQL
- name: Install MySQL-python
  action: "{{ packager }} pkg={{ mysql_python }} state=present"

- name: Check for /root/my.cnf
  stat: path=/root/my.cnf
  register: mycnf

- name: Copy /root/my.cnf
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600
  when: mycnf.stat.exists == false
- name: Copy ~/my.cnf
  template: src=my.cnf dest=/home/{{ item }}/.my.cnf owner={{ item }} mode=0600
  with_items: administrators
  when: mycnf.stat.exists == false

- name: Reset /root/my.cnf's root password on install
  lineinfile: dest=/root/my.cnf regexp='^password='  line="password="
  when: mycnf.stat.exists == false
- name: Reset ~/my.cnf's root password on install
  lineinfile: dest=/home/{{ item }}/.my.cnf regexp='^password='  line="password="
  with_items: administrators
  when: mycnf.stat.exists == false

- name: Set MySQL Root
  mysql_user: name=root host="{{ item }}" password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
  - "{{ hostname }}"
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

- name: Copy ~/my.cnf to root
  template: src=my.cnf dest=/root/.my.cnf owner=root group=root mode=0600
- name: Copy ~/my.cnf to Administrator
  template: src=my.cnf dest=/home/{{ item }}/.my.cnf owner={{ item }} group={{ item }} mode=0600
  with_items: administrators

- name: Delete anonymous MySQL server user for {{ ansible_hostname }}
  action: mysql_user user="" host="{{ item }}" state="absent"
  with_items:
  - "{{ hostname }}"
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost
- name: Delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"
- name: Remove the MySQL test database
  action: mysql_db db=test state=absent
