---
- name: Install MySQL
  apt: pkg=mysql-server state=present
- name: Run MySQL on boot
  service: name=mysql enabled=yes state=started
- name: Install MySQL-python
  apt: pkg=python-mysqldb state=present

- name: Check for /root/.my.cnf
  stat: path=/root/.my.cnf
  register: mycnf

- name: Copy /root/.my.cnf
  template: src=my_user.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  when: mycnf.stat.exists == false
- name: Copy ~/.my.cnf
  template: src=my_user.cnf.j2 dest=/home/{{ item }}/.my.cnf owner={{ item }} mode=0600
  with_items: administrators | default([])
  when: mycnf.stat.exists == false

- name: Reset /root/.my.cnf's root password on install
  lineinfile: dest=/root/.my.cnf regexp='^password='  line="password="
  when: mycnf.stat.exists == false
- name: Reset ~/.my.cnf's root password on install
  lineinfile: dest=/home/{{ item }}/.my.cnf regexp='^password='  line="password="
  with_items: administrators | default([])
  when: mycnf.stat.exists == false

- name: Set MySQL Root
  mysql_user: name=root host="{{ item }}" password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
  - "{{ hostname }}"
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

- name: Copy ~/.my.cnf to root
  template: src=my_user.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
- name: Copy ~/.my.cnf to Administrator
  template: src=my_user.cnf.j2 dest=/home/{{ item }}/.my.cnf owner={{ item }} group={{ item }} mode=0600
  with_items: administrators | default([])

- name: Delete anonymous MySQL server user for {{ ansible_hostname }}
  action: mysql_user user="" host="{{ item }}" state="absent"
  with_items:
  - "{{ hostname }}"
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost
- name: Delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"
- name: Remove the MySQL test database
  action: mysql_db db=test state=absent

- name: Configure MySQL
  template: src=my.cnf.j2 dest=/etc/mysql/conf.d/z_ansible.cnf
  notify: Restart MySQL

- name: Allow MySQL connections from external IPs
  ufw: rule=allow port=3306 src={{ item }}
  with_items: database.exposed
  when: database.exposed != false

- name: Allow MySQL connections from other devboxes
  ufw: rule=allow port=3306 src=10.0.0.0/24
  when: "'development' in group_names"
