---
- name: Install the Git Maintainers PPA
  apt_repository: repo='ppa:git-core/ppa' update_cache=no
- name: Install an updated PPA for Tmux and Vim
  apt_repository: repo='ppa:pi-rho/dev' update_cache=no
- name: Update the Apt cache
  apt: update_cache=yes

- name: Install some development tools
  apt: pkg={{ item }} state=latest
  with_items:
  - tmux
  - zsh
  - vim
  - git-core
  - graphviz
  - man

- name: Clone setup-site application
  git: repo=https://github.com/SpenserJ/Webhost-Setup-Site-Scripts.git
       dest=/usr/local/bin/setup-site
       accept_hostkey=yes
- name: Install setup-site dependencies
  npm: path=/usr/local/bin/setup-site state=latest
- name: Symlink setup-site Application
  file: src=/usr/local/bin/setup-site/setup-site
        path=/usr/bin/setup-site
        state=link
