---
- name: Clone setup-site application
  git: repo=https://github.com/SpenserJ/Webhost-Setup-Site-Scripts.git
       dest=/usr/local/bin/setup-site
       accept_hostkey=yes
- name: Install setup-site dependencies
  npm: path=/usr/local/bin/setup-site state=latest
- name: Symlink setup-site Application
  file: src=/usr/local/bin/setup-site/setup-site
        path=/usr/bin/setup-site
        state=link

- name: Clone PHP Code Sniffer
  git: repo=https://github.com/squizlabs/PHP_CodeSniffer.git
       dest=/usr/local/src/phpcs
       accept_hostkey=yes
- name: Symlink PHPCS
  file: src=/usr/local/src/phpcs/scripts/phpcs dest=/usr/local/bin/phpcs state=link

- name: Install the Drupal Coder module to Shared Drush
  command: drush pm-download -y coder-8.x-2.3 --destination="/usr/share/drush/commands"
- name: Symlink the Drupal Standards into PHP Code Sniffer's Standards
  file: src=/usr/share/drush/commands/coder/coder_sniffer/Drupal
        dest=/usr/local/src/phpcs/CodeSniffer/Standards/Drupal
        state=link

- name: Install NPM packages used for linting source code
  npm: name={{ item }} global=yes
  with_items:
  - esprima
  - eslint
  - jshint

- name: Clone the Code Quality Hooks repository
  git: repo=https://github.com/SpenserJ/Code-Quality-Hooks.git
       dest=/usr/local/src/code-quality-hooks
       accept_hostkey=yes
- name: Install the Code Quality Hooks dependencies
  npm: path=/usr/local/src/code-quality-hooks production=yes
- name: Symlink the Post Commit hook to the git hook templates
  file: src=/usr/local/src/code-quality-hooks/code-quality-post-commit.js
        dest=/usr/share/git-core/templates/hooks/post-commit
        state=link
        force=true
- name: Symlink the Post Commit hook to all configured websites
  shell: "for dir in $(find /var/www/shared -maxdepth 3 -type d -path \"*/public_html/.git\"); do ln --force -s /usr/local/src/code-quality-hooks/code-quality-post-commit.js  \"$dir/hooks/post-commit\"; done"
  args:
    executable: /bin/bash
