---
- name: Ensure /etc/ssl/webserver-certs/ exists
  file: path=/etc/ssl/webserver-certs state=directory owner=root group=root
- name: Copy any SSL certificates that are provided by a website
  copy: src={{ item.value.ssl }} dest=/etc/ssl/webserver-certs/{{ item.key | replace('__hostname__', hostname) }}.crt
  when: item.value.ssl is defined
  with_dict: websites
