---
- name: Node.js | Exists
  stat: path=/usr/bin/node
  register: installed_node
- name: Node.js | Download source
  get_url: url=http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz dest=/tmp/
  when: installed_node.stat.exists == false
- name: Node.js | Extract tarball
  command: tar -zxf /tmp/node-v0.10.24.tar.gz chdir=/tmp
  when: installed_node.stat.exists == false
- name: Node.js | Configure
  shell: ./configure --prefix=/usr chdir=/tmp/node-v0.10.24
  when: installed_node.stat.exists == false
- name: Node.js | Make
  shell: make chdir=/tmp/node-v0.10.24
  when: installed_node.stat.exists == false
- name: Node.js | Make install
  shell: make install chdir=/tmp/node-v0.10.24
  when: installed_node.stat.exists == false
- name: Node.js | Gulp exists
  stat: path=/usr/bin/gulp
  register: installed_gulp
- name: Node.js | Install gulp
  command: npm install -g gulp
  when: installed_gulp.stat.exists == false
