---
# Uninstall Mailpile
- name: Remove PostFix
  apt: pkg=postfix state=absent purge=yes
- name: Remove Mailpile autostart
  lineinfile: dest="/etc/rc.local"
              line="python2.7 /etc/mailpile/mp"
              state=absent
- name: Remove Mailpile configuration
  file: path=/root/.local/share/Mailpile state=absent
- name: Remove Mailpile repository
  file: path=/etc/mailpile state=absent

- name: Block outbound email
  ufw: rule=reject port={{ item }} direction=out
  with_items:
  - 25
  - 465
  - 587
