---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Update Apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install packages we depend on
  action: "{{ packager  }} pkg={{ item }} state=present"
  with_items:
  - acl
  - python-pycurl
  - htop
  - '{{ build_essential }}'

- name: Set Hostname for this boot
  shell: hostname {{ hostname }}
- name: Set Hostname permanently
  template: src=hostname.j2 dest=/etc/hostname

- name: Set Hostname in /etc/hosts
  lineinfile: "dest=/etc/hosts line='127.0.0.1 {{ hostname }}'"

- name: Set timezone to America/Edmonton
  file: path=/etc/localtime src=/usr/share/zoneinfo/America/Edmonton state=link force=yes
