---
- name: Update Apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == 'Debian'
- name: Install packages we depend on
  apt: pkg={{ item }} state=present
  with_items:
  - acl
  - python-pycurl
  - htop
  when: ansible_os_family == 'Debian'

- name: Set Hostname for this boot
  shell: hostname {{ hostname }}
- name: Set Hostname permanently
  template: src=hostname.j2 dest=/etc/hostname
- name: Set Hostname for eth1
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth1
              regexp='^DHCP_HOSTNAME={{ hostname }}'
              line='DHCP_HOSTNAME={{ hostname }}'
              insertbefore=BOF
  when: ansible_os_family == 'RedHat'

- name: Set timezone to America/Edmonton
  file: path=/etc/localtime src=/usr/share/zoneinfo/America/Edmonton state=link force=yes

- name: Ensure the admin group exists
  group: name=admin
