- name: Have we installed Drush via Pear before
  stat: path="{{ pear_folder }}/.channels/pear.drush.org.reg"
  register: installed_drush
- name: Uninstall Pear Drush
  command: pear uninstall drush/drush
  when: installed_drush.stat.exists == true
- name: Delete Drush Channel
  command: pear channel-delete pear.drush.org
  when: installed_drush.stat.exists == true

- name: Clone Drush repository
  git: repo=https://github.com/drush-ops/drush.git
       dest=/usr/local/src/drush
       version=7.0.0
       accept_hostkey=yes
       force=yes

# https://github.com/ansible/ansible-modules-extras/issues/338
- name: Copy Drush Autoslave patch as workaround for Ansible 1.9 bug
  copy: src=drush_autoslave.patch dest=/tmp/drush_autoslave.patch
- name: Patch Drush for AutoSlave support
  patch: src=/tmp/drush_autoslave.patch basedir=/usr/local/src/drush strip=1 remote_src=True

- name: Install Drush dependencies
  composer: command=install working_dir=/usr/local/src/drush
- name: Link Drush to /usr/bin
  file: src=/usr/local/src/drush/drush dest=/usr/bin/drush state=link
