---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Load Apache role's vars for this distro
  include_vars: "roles/apache2/vars/{{ ansible_os_family }}.yml"

- name: Get PHP PPA
  apt_repository: repo="ppa:ondrej/php5"
  when: ansible_os_family == "Debian"

- name: Install PHP
  action: "{{ packager }} pkg={{ php }} state=present"
- name: Install PHP Extensions
  action: "{{ packager }} pkg={{ item }} state=present"
  with_items:
  - "{{ php }}-curl"
  - "{{ php }}-mcrypt"
  - "{{ php }}-gd"
  - "{{ php }}-imap"
  - "{{ php }}-intl"
  - "{{ php }}-xmlrpc"
  - "{{ php_dev }}"
  - "{{ php_mysql }}"
  - php-pear
  notify:
  - restart apache2
- name: Install PHP Extensions for Developers
  action: "{{ packager }} pkg={{ item }} state=present"
  with_items:
  - "{{ php }}-xhprof"
  - "{{ php_xdebug }}"
  when: "'development' in group_names"
  notify:
  - restart apache2


- name: Install PHP 5.3 Extensions
  action: "{{ packager }} pkg={{ php }}-{{ item }} state=present"
  with_items:
  - mbstring
  - pdo
  - xml
  when: ansible_os_family == "RedHat"

- name: Configure php.ini
  template: src=php.ini.j2 dest=/etc/php.ini
  when: apache
  notify:
  - restart apache2
- name: Configure xdebug.ini
  copy: src=xdebug.ini dest={{ php_mod_config }}/xdebug.ini
  when: "'development' in group_names"
  notify:
  - restart apache2
- name: Enable PHP configuration in Apache
  template: src=php5.conf.j2 dest="{{ apache2_conf_folder }}/php5.conf"
  when: apache
  notify:
  - restart apache2

- name: Ensure sessions folder exists
  file: path={{ php_sessions }} state=directory mode=1733
  notify:
  - restart apache2
  - restart php-fpm

- name: Run PHP FPM Tasks
  include: fpm.yml
  when: nginx

- name: Run Drush Tasks
  include: drush.yml
