---
- name: Load vars for this distro
  include_vars: "{{ ansible_os_family }}.yml"
- name: Load Apache role's vars for this distro
  include_vars: "roles/apache2/vars/{{ ansible_os_family }}.yml"

- name: Get PHP PPA
  apt_repository: repo="ppa:ondrej/php5"
  when: ansible_os_family == "Debian"

- name: Install PHP
  action: "{{ packager }} pkg={{ php }} state=present"
- name: Install PHP Extensions
  action: "{{ packager }} pkg={{ item }} state=present"
  with_items:
  - "{{ php }}-curl"
  - "{{ php }}-mcrypt"
  - "{{ php }}-xhprof"
  - "{{ php }}-gd"
  - "{{ php }}-imap"
  - "{{ php_dev }}"
  - "{{ php_xdebug }}"
  - "{{ php_mysql }}"
  - php-pear
  notify:
  - restart apache2

- name: Install PHP 5.3 Extensions
  action: "{{ packager }} pkg={{ php }}-{{ item }} state=present"
  with_items:
  - mbstring
  - pdo
  - xml
  when: ansible_os_family == "RedHat"

- name: Configure php.ini
  copy: src=php.ini dest=/etc/php.ini
  notify:
  - restart apache2
- name: Configure xdebug.ini
  copy: src=xdebug.ini dest={{ php_mod_config }}/xdebug.ini
  notify:
  - restart apache2
- name: Enable PHP configuration in Apache
  template: src=php5.conf.j2 dest="{{ apache2_conf_folder }}/php5.conf"
  notify:
  - restart apache2

- name: Have we installed Drush before
  stat: path="{{ pear_folder }}/.channels/pear.drush.org.reg"
  register: installed_drush
- name: Discover Drush Channel
  command: pear channel-discover pear.drush.org
  when: installed_drush.stat.exists == false
- name: Install Drush
  command: pear install drush/drush
  when: installed_drush.stat.exists == false
- name: Prepare Drush for use
  command: drush
  when: installed_drush.stat.exists == false
